added deploy-gcp

diff --git a/.github/workflows/deploy-aws.yml b/.github/workflows/deploy-aws.yml
--- a/.github/workflows/deploy-aws.yml
+++ b/.github/workflows/deploy-aws.yml
@@ -59,10 +59,13 @@ jobs:
      - name: Build Spring Boot App
        working-directory: spring-boot-server
        run: mvn clean package -DskipTests
-    
-     - name: Verify Build Artifact
-       run: ls -R spring-boot-server
+      
+     - name: List build outputs
+       run: |
+        ls -R react-frontend/build || echo "Frontend build missing"
+        ls -R spring-boot-server/target || echo "Backend JAR missing"
 
+        
       # ---------- DEPLOY ----------
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
